### PR TITLE
Improve deployment

### PR DESCRIPTION
**Pull request by zachkont**
This will also address https://github.com/TimJentzsch/valveGamesAnnouncerBot/issues/37 by adding several try-catch blocks.

After investigating, the main issue seems to be with the reddit api wrapper. Even when set up using the [Reddit oAuth Helper](https://not-an-aardvark.github.io/reddit-oauth-helper/?state=q8EtLAfYyPzP1TWswixuwOcWrr4qooQJOJGkLhBmTgc%3D&code=LDSTu2iNTXgQxsaoS2s15B8_UqI) and the initialization completes successfully, authentication/authorization errors are returned from the `getUser().getSubmissions()` line.

### CODE REVIEW

**Comment by zachkont** [comment]
I don't now of a reliable way to make `rm` commands work cross-platform. We can either remove them entirely, replace them with custom scripts or leave them in and accept the fact that they will only work for linux systems. I vote for the latter.

**Comment by TimJentzsch** [comment]
What about using something like [shelljs](https://www.npmjs.com/package/shelljs) or [rimraf](https://www.npmjs.com/package/rimraf)?

**Comment by zachkont** [comment]
I don't know how to reliably use an npm module to delete the `node_modules/` directory. We could use it for deleting `dist/` only and I think that makes the most sense, and get rid of `yarn clean` entirely

**Comment by TimJentzsch** [comment]
Sure, let's do that.

**Comment by zachkont** [comment]
> I'd maybe do `yarn install` before `yarn demolish`, but this works fine now.

That's better indeed, fixed

**Pull request merged**
